### PR TITLE
Add passive air exchanger efficiency for all devices

### PR DESCRIPTION
**Pull request by gllmlbrt**
I think this sensor is relevant for all machines, but feel free to restrict it only to COMFORT.
Tested and works fine.
image

### CODE REVIEW

**Review by veista — CHANGES_REQUESTED** [review]
get_exchanger_efficiency would be more describing. custom_components/nilan/device_map.py, items are in register order and I would like to keep it that way.

**Comment by gllmlbrt** [comment]
Will do the change. "air_temp_eff_pct" is the term used by Nilan in the protocol, otherwise I agree with you.

**Comment by veista** [comment]
Yes, they are not easy to remember or very describing.

**Comment by veista** [comment]
By the way, my device does not have a passive exchanger and the efficiency still shows. Thanks!

**Comment by gllmlbrt** [comment]
> my device does not have a passive exchanger and the efficiency still shows. Thanks!

Maybe we should then only point to the COMFORT series (13) ?

Changes done now.

**Comment by veista** [comment]
> > my device does not have a passive exchanger and the efficiency still shows. Thanks!
> 
> Maybe we should then only point to the COMFORT series (13) ?
> 
> Changes done now.

No, I mean that it works! Did not notice this feature.

**Review by veista — APPROVED** [review]

**Comment by abstacek** [comment]
I wondered what to add the air calculation too?

DPT.AirFlow1 2201 m3/h Calculated air flow 1
DPT.AirFlow2 2202 m3/h Calculated air flow 2

**Pull request merged**
